import React from 'react';
import { BrowserRouter as Router, Switch } from 'react-router-dom';
import {
  Home,
  Login,
  Tutors,
  Register,
  State,
  VideoCall,
  TutorInfo,
  Scheduler,
  Introduction,
  Reservation,
  TutorScheduler,
  TutorSignUpProcedure,
  TutorSignUpHome,
  TutorSignUpAccount,
  Subcription,
  Checkout,
  TutorLogin,
  TutorRegister,
  History,
  Review,
} from '../containers';
import { MyInfo } from '../components/MyInfo/MyInfo';
import { PrivateRouter } from './PrivateRouter';
import { PublicRouter } from './PublicRouter';
import { BlankLayout, HeaderFooterLayout, OnlyFooterLayout, OnlyHeaderLayout } from '../layouts';
import { Header, Footer, HeaderTutor, HeaderHome } from '../components/common';
export const Routers = () => {
  const buildysURL = process.env.REACT_APP_LINK_BUILDYS;

  return (
    <State>
      <Router>
        <Switch>
          <PublicRouter
            exact={true}
            path={'/'}
            component={Introduction}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={HeaderHome}
            isHasFooter={true}
            footer={Footer}
          />
          <PrivateRouter
            exact={true}
            path={'/log-out'}
            component={Home}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PublicRouter
            exact={true}
            path={'/call'}
            component={VideoCall}
            layout={HeaderFooterLayout}
            isHasHeader={false}
            header={Header}
            isHasFooter={false}
            footer={Footer}
          />
          <PublicRouter
            exact={true}
            path={'/student/tutors'}
            component={Tutors}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PublicRouter
            exact={true}
            path={'/student/tutors/:id'}
            component={TutorInfo}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
        </Switch>

        <Switch>
          <PublicRouter
            exact={true}
            path={'/student/register'}
            component={Register}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={HeaderHome}
            isHasFooter={true}
            footer={Footer}
          />
          <PublicRouter
            exact={true}
            path={'/student/login'}
            component={Login}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={HeaderHome}
            isHasFooter={true}
            footer={Footer}
          />
          <PrivateRouter
            exact={true}
            path={'/student/subcribe'}
            component={Subcription}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PrivateRouter
            exact={true}
            path={'/student/checkout'}
            component={Checkout}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PrivateRouter
            exact={true}
            path={'/student/review'}
            component={Review}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PrivateRouter
            exact={true}
            path={'/student'}
            component={Home}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PrivateRouter
            exact={true}
            path={'/student/schedule'}
            component={Scheduler}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PrivateRouter
            exact={true}
            path={'/student/schedule/:id'}
            component={Scheduler}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
        </Switch>

        <Switch>
          <PublicRouter
            exact={true}
            path={'/tutor/login'}
            component={TutorLogin}
            layout={OnlyHeaderLayout}
            isHasHeader={true}
            header={HeaderTutor}
            isHasFooter={false}
          />
          <PublicRouter
            exact={true}
            path={'/tutor/register'}
            component={TutorRegister}
            layout={OnlyHeaderLayout}
            isHasHeader={true}
            header={HeaderTutor}
            isHasFooter={false}
          />
          <PublicRouter
            exact={true}
            path={'/tutor/reservation'}
            component={Reservation}
            layout={OnlyHeaderLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={false}
          />
          <PublicRouter
            exact={true}
            path={'/tutors/schedule/create'}
            component={TutorScheduler}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PublicRouter
            exact={true}
            path={'/tutors/schedule/create/:id'}
            component={TutorScheduler}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PublicRouter
            exact={true}
            path={'/tutors/profile/me'}
            component={MyInfo}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
          <PublicRouter path="/tutors" component={TutorSignUpHome} layout={BlankLayout} exact />
          <PublicRouter path="/tutor/:path?" component={TutorSignUpAccount} layout={BlankLayout} />
          <PrivateRouter
            path="/tutorsignup/:path?"
            component={TutorSignUpProcedure}
            layout={BlankLayout}
          />
          <PublicRouter
            exact={true}
            path={'/student/history'}
            component={History}
            layout={HeaderFooterLayout}
            isHasHeader={true}
            header={Header}
            isHasFooter={true}
            footer={Footer}
          />
        </Switch>
      </Router>
    </State>
  );
};
